### ISSUE TITLE
Encoding errors when message body contains unicode

### ISSUE THREAD

**Issue by edyburn** [fengsp/sender#3]
Is there a reason the utf-8 charset is overridden to remove the body encoding? (https://github.com/fengsp/sender/blob/928d289ed33f369a856cb108cf5511fc3091d933/sender.py#L26) This seems to cause encoding errors when the body contains non-ascii characters, at least on python3.

```python-traceback
  File "python3.4/lib/python3.4/site-packages/sender.py", line 97, in send
    c.send(message)
  File "python3.4/lib/python3.4/site-packages/sender.py", line 147, in send
    message.mail_options, message.rcpt_options)
  File "/usr/lib/python3.4/smtplib.py", line 765, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character 'u2019' in position 491: ordinal not in range(128)
```

I've worked around this by restoring the defaults:
```python
charset.add_charset('utf-8', charset.SHORTEST, charset.BASE64, 'utf-8')
```

**Comment by eka** [comment]
Same happens to me, changing that line fixes the problem.

**Comment by fengsp** [comment]
Python 3.x is not supported yet.
